name: "[Plugin] on-push-dev"

on:
  push:
    branches:
      - dev
    paths:
      - 'plugin/**'
      - 'plugin-ui/**'

jobs:
  build-mac:
    uses: ./.github/workflows/[plugin] build-mac.yml
    secrets:
      APPLE_EMAIL: ${{ secrets.APPLE_EMAIL }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      DEVELOPER_ID_APPLICATION_BASE64: ${{ secrets.DEVELOPER_ID_APPLICATION_BASE64 }}
      DEVELOPER_ID_INSTALLER_BASE64: ${{ secrets.DEVELOPER_ID_INSTALLER_BASE64 }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

  build-win:
    uses: ./.github/workflows/[plugin] build-win.yml
