name: "[Plugin] build-win"

# on:
#   workflow_call:
on:
  push:
    branches:
      - dev

jobs:
  build-win-all:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Init submodules, download dependencies
        shell: bash
        run: |
          cd plugin

          git submodule init
          git submodule update

          cd iPlug2/Dependencies/IPlug
          ./download-iplug-sdks.sh

      # - name: Build frontend
      #   run: |
      #     cd plugin-ui
      #     npm i
      #     npm run build

      # - name: Build and sign VST3
      #   run: |
      #     cd plugin/Straudio
      #     msbuild Straudio.sln -target:Straudio-vst3 /property:Configuration=Release

      # - name: Build and sign app
      #   run: |
      #     cd plugin/Straudio
      #     msbuild Straudio.sln -target:Straudio-app /property:Configuration=Release
      
      - name: Build Release Artifacts
        run: |
          cd plugin/Straudio
          ./scripts/makedist-win.bat 0

      # - name: Zip
      #   run: |
      #     cd plugin/Straudio/build-mac
      #     zip -r Straudio.app.zip Straudio.app
      #     zip -r Straudio.component.zip Straudio.component
      #     zip -r Straudio.vst3.zip Straudio.vst3

      # - name: Upload the artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: |
      #       plugin/Straudio/build-mac/Straudio.app.zip
      #       plugin/Straudio/build-mac/Straudio.component.zip
      #       plugin/Straudio/build-mac/Straudio.vst3.zip
      #       plugin/Straudio/build-mac/Straudio-mac.dmg
