name: "[Plugin] on-push-main"

on:
  push:
    branches:
      - main
    paths:
      - 'plugin/**'
      - 'plugin-ui/**'

jobs:
  build-mac:
    uses: ./.github/workflows/[plugin] build-mac.yml
    secrets:
      APPLE_EMAIL: ${{ secrets.APPLE_EMAIL }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      DEVELOPER_ID_APPLICATION_BASE64: ${{ secrets.DEVELOPER_ID_APPLICATION_BASE64 }}
      DEVELOPER_ID_INSTALLER_BASE64: ${{ secrets.DEVELOPER_ID_INSTALLER_BASE64 }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

  build-win:
    uses: ./.github/workflows/[plugin] build-win.yml

  upload-prerelease:
    runs-on: macos-latest
    permissions: write-all
    needs: build-release
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}-pre
          body: ${{ steps.tag_version.outputs.changelog }}
          prerelease: true
          generateReleaseNotes: true
          artifacts: |
            build-artifacts/Straudio-mac.dmg
            build-artifacts/Straudio-mac.app.zip
            build-artifacts/Straudio-mac.component.zip
            build-artifacts/Straudio-mac.vst3.zip
            build-artifacts/Straudio-win.vst3.zip
            build-artifacts/Straudio-win.exe
            build-artifacts/Straudio-winInstaller.exe

