name: Build Release

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 0 * * *'

# If CI ever becomes too cumbersome, revert to running this script more sparingly:
# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'plugin/**'

jobs:
  build-release:
    runs-on: macos-latest
    env:
      APPLE_EMAIL: ${{ secrets.APPLE_EMAIL }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

    steps:
      - name: Print Xcode version
        run: xcodebuild -version

      - name: Print notarytool version
        run: xcrun notarytool --version

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Release Image
        run: |
          # Move to plugin directory
          cd plugin

          # Initialize submodules
          git submodule init
          git submodule update

          # Download IPlug SDKs
          cd iPlug2/Dependencies/IPlug
          ./download-iplug-sdks.sh

          # Go back to the root of the plugin directory
          cd ../../../Straudio

          # Run your build script
          ./scripts/makedist-mac.sh
