name: Dev

on:
  push:
    branches:
      - dev
    # paths:
    #   - 'plugin/**'
    #   - 'plugin-ui/**'

jobs:
  build-release:
    uses: ./.github/workflows/plugin::build-mac.yml
    secrets:
      APPLE_EMAIL: ${{ secrets.APPLE_EMAIL }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      DEVELOPER_ID_APPLICATION_BASE64: ${{ secrets.DEVELOPER_ID_APPLICATION_BASE64 }}
      DEVELOPER_ID_INSTALLER_BASE64: ${{ secrets.DEVELOPER_ID_INSTALLER_BASE64 }}
      BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

  upload:
    runs-on: macos-latest
    needs: build-release
    steps:
      - name: Upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            ${{ needs.build-release.outputs.vst-path }}
            ${{ needs.build-release.outputs.app-path }}
            ${{ needs.build-release.outputs.pkg-path }}
            ${{ needs.build-release.outputs.au-path }}
